singnet/das-query-engine

hyperon_das/api.py
hyperon_das/factory.py

Resolves singnet/das-atom-db#8

[das-atom-db #8] Improvement / change hash_table to ram_only when need

---

Makefile
hyperon_das/factory.py
tests/mock.py
tests/test_api.py
tests/test_pattern_matcher.py

[# 21] Improvement / Add unit test to Patternmatcher and DistributedAtomSpace

---

.gitignore
hyperon_das/api.py
tests/test_api.py

[# 18] Improvement / Refactor return type

---

hyperon_das/api.py
hyperon_das/cache.py
hyperon_das/logger.py
hyperon_das/pattern_matcher/pattern_matcher.py
hyperon_das/utils.py
tests/test_api.py
tests/test_cache.py
tests/test_utils.py

[#40] Improvement / Add logs in Das

---

hyperon_das/api.py

Catch exception when unknown node is queried

Quick fix for bug reported in #6

---

hyperon_das/client.py
hyperon_das/das.py

[#33] Change type hint

---

hyperon_das/client.py

[#76] Remove pipe

---

Makefile
hyperon_das/utils.py
poetry.lock
pyproject.toml

[#44] Enhancement / refactor makefile

---

.github/workflows/publish-pypi.yml

Configured the library name for use in Mattermost notifications.

ci: set library name

---

.github/workflows/publish-pypi.yml

* Add the changelog manually (this will be used in the message sent to the mattermost)

ci: manual changelog

---

hyperon_das/client.py
hyperon_das/das.py
hyperon_das/query_engines.py
tests/unit/mock.py
tests/unit/test_das.py

[#97] Add get_incoming_link on the Das Api

---

.github/workflows/publish-pypi.yml

* Fix changelog typo in workflow

ci: changelog typo

---

hyperon_das/query_engines.py
tests/integration/test_client.py
tests/integration/test_remote_das.py

[#71] New integration tests in remote Das

---

tests/integration/test_local_redis_mongo.py

WIP - this PR don't fix bug #114  it just adds a helpful test

[#114] Added test to check persistence in local DBs after add_atom()

---

hyperon_das/das.py
hyperon_das/query_engines.py

[#39] Add reindex() to rebuild pattern index in local DAS

---

CHANGELOG
pyproject.toml
tests/integration/test_metta_api.py

Resolves #122 
The test case added in this PR is the one required to test https://github.com/singnet/das-query-engine/issues/120
Required by https://github.com/singnet/das-query-engine/issues/120

[#122] Add integration test to DAS API used by MeTTa

---

.github/workflows/publish-pypi.yml

[#127][#128] Fix mattermost message

---

README.md

* Add in README.md a link to github releases

[das-atom-db#82] Add Query Engine Release Notes

---

CHANGELOG
pyproject.toml

[#134] Update package version

---

CHANGELOG
hyperon_das/cache.py
hyperon_das/query_engines.py
hyperon_das/traverse_engines.py
tests/integration/test_remote_das.py
tests/integration/test_traverse_engine.py

[#139] Update TraveseEngine to use IncomingLinksIterators

---

CHANGELOG
hyperon_das/cache.py
tests/integration/test_traverse_engine.py

[#145] Refactor TraverseNeighborsIterator

---

hyperon_das/cache.py
hyperon_das/client.py
hyperon_das/das.py
hyperon_das/query_engines.py
hyperon_das/traverse_engines.py
tests/integration/test_metta_api.py
tests/integration/test_remote_das.py
tests/integration/test_traverse_engine.py
tests/unit/test_cache.py
tests/unit/test_client.py

[#147] Create an iterator for get_links()

---

CHANGELOG
hyperon_das/__init__.py
hyperon_das/das.py
hyperon_das/utils.py
tests/integration/test_client.py
tests/integration/test_remote_das.py
tests/integration/test_traverse_engine.py
tests/unit/test_das.py

[#160] Add about() method in DAS

---

CHANGELOG
hyperon_das/query_engines.py
tests/integration/remote_das_info.py
tests/integration/test_client.py

Resolves #156
Required vor https://github.com/singnet/das-metta-parser/issues/30

[#156] Fix MeTTa->Nodes/Links mapping

---

CHANGELOG
hyperon_das/das.py
hyperon_das/query_engines.py
tests/integration/test_client.py
tests/integration/test_remote_das.py
tests/integration/test_traverse_engine.py

[#173] Change the type hint in query()

---

.github/workflows/pull-request.yml

Closes https://github.com/singnet/das/issues/16

[das#16] Remove integration tests from the workflows and add them at the end of the release script

---

CHANGELOG
hyperon_das/utils.py

[#210] Improve message error when connecting to the server

---

hyperon_das/query_engines.py
tests/integration/test_remote_das.py
tests/unit/test_queries.py

[#235] Remove tuple in return and change type hint

---

CHANGELOG
hyperon_das/cache.py
hyperon_das/das.py
hyperon_das/query_engines.py
hyperon_das/utils.py
tests/integration/test_remote_das.py
tests/unit/mock.py

[#214 ] Improve fetch() method to optionally fetch all the atoms

---

hyperon_das/cache/__init__.py
hyperon_das/cache/cache_manager.py
hyperon_das/cache/iterators.py
hyperon_das/das.py
hyperon_das/query_engines.py
hyperon_das/traverse_engines.py
tests/integration/test_iterators.py
tests/unit/test_cache.py

Got iterators and cache_manager separated and added together in a new package named 'cache'.
Related to #108

[#108] WIP - Got iterators and cache_manager separated in new package `cache`

---

CHANGELOG
hyperon_das/query_engines.py
pyproject.toml
tests/integration/helpers.py
tests/integration/test_client.py
tests/integration/test_iterators.py
tests/integration/test_remote_das.py
tests/unit/mock.py

[#241] Fix integration tests

---

hyperon_das/__init__.py
hyperon_das/client.py
hyperon_das/context.py
hyperon_das/das.py
hyperon_das/query_engines.py
tests/unit/test_client.py
tests/unit/test_context.py
tests/unit/test_das.py

Resolves #245 
Related to #108

[#245] Add create_context() command in DAS (WIP)

---

.github/workflows/publish-pypi.yml

Closes https://github.com/singnet/das/issues/6

[das#6] Migrate contents of das-scripts-pipeline to das

---

hyperon_das/context.py
hyperon_das/das.py
tests/unit/test_cache_controller.py
tests/unit/test_context.py

[#256] Change the key in the context_node and change default value in the type hint

---

.github/workflows/publish-pypi.yml

Closes https://github.com/singnet/das/issues/22

[das#22] Add title and deliverable message to versioning job

---

docs/DAS-Overview.md
mkdocs.yml
pyproject.toml

[#263] Some images in the query engine documentation are not loading

---

CHANGELOG
hyperon_das/cache/iterators.py
hyperon_das/das.py
hyperon_das/query_engines.py
hyperon_das/traverse_engines.py
tests/integration/test_remote_das.py
tests/integration/test_traverse_engine.py

- Tiny refactor to the DAS constructor
- Add private attribute in RemoteQueryEngine
Resolves #218

Make a DAS server read-only

---

.github/workflows/publish-pypi.yml

Closes https://github.com/singnet/das-atom-db/issues/125

[das-atom-db#125] ci: change step name

---

hyperon_das/das.py
hyperon_das/traverse_engines.py

Added Kwargs documentation
closes #223

[das-query-engine#223] Updated kwargs documentation

---

tests/performance/run_perf_tests.sh

relates to #268 
Adding results comparison to the scripts which runs MeTTa perf tests.

[#268] enhancing perf tests script, added results comparison

---

hyperon_das/client.py
tests/unit/test_client.py

Removing none values from payload due to String can't be None on faas

[HOTFIX] Fix integration tests

---

.github/workflows/publish-pypi.yml
.github/workflows/run-tests.yml

Closes https://github.com/singnet/das/issues/56

[#56] Review release process

---

.github/workflows/run-tests.yml

Closes https://github.com/singnet/das/issues/59

[#59] Separate Tests and Lint into Individual jobs on pipeline

---

hyperon_das/constants.py
hyperon_das/das.py

Refactor DAS Class: Replace das_type string with Enum and update all references

---

hyperon_das/client.py
hyperon_das/das.py
hyperon_das/query_engines/local_query_engine.py
hyperon_das/query_engines/remote_query_engine.py
pyproject.toml
tests/integration/test_remote_das.py
tests/unit/mock.py

Replace NodeDoesNotExist and LinkDoesNotExist by AtomDoesNotExist

---

Makefile
README.md
tests/conftest.py
tests/performance/test_mongo_redis_performance.py

Added queries to benchmark mongo and redis
how to run:
`make benchmark-tests`
for more options please read the README

[atom-db #150] Query benchmark

---

Makefile
README.md
tests/performance/metta_files_generator.py
tests/performance/test_mongo_redis_performance.py

Added MakeFile command to generate MeTTa files

[atom-db #150] Create MeTTa files

---

CHANGELOG
hyperon_das/client.py
hyperon_das/das.py
hyperon_das/query_engines/local_query_engine.py
hyperon_das/query_engines/query_engine_protocol.py
hyperon_das/query_engines/remote_query_engine.py
tests/integration/test_client.py
tests/integration/test_remote_das.py
tests/unit/test_client.py

[#308] Change get_node() and get_link() to reuse get_atom()

---

hyperon_das/client.py
hyperon_das/das.py
hyperon_das/query_engines/local_query_engine.py
hyperon_das/query_engines/remote_query_engine.py
hyperon_das/traverse_engines.py
tests/integration/test_client.py
tests/integration/test_iterators.py
tests/unit/test_das.py

Closes #317 
- Ensures that integration tests are passing green.

[#317] fixing integration tests

---

hyperon_das/das.py
tests/integration/test_client.py
tests/integration/test_remote_das.py

Resolves https://github.com/singnet/das-query-engine/issues/324
A couple of other skipped tests (not in the scope of #324 ) have also been fixed and un-skipped.

[#324] Re-enable commented out test cases

---

tests/performance/test_redis_mongo_benchmark.py

Added random parameters
Added TraverseEngine queries

[atom-db#150] Added TraverseEngine performance queries

---

hyperon_das/cache/iterators.py
hyperon_das/das.py
hyperon_das/query_engines/local_query_engine.py
hyperon_das/query_engines/query_engine_protocol.py
hyperon_das/query_engines/remote_query_engine.py
hyperon_das/traverse_engines.py
tests/integration/test_iterators.py
tests/integration/test_traverse_engine.py
tests/unit/test_traverse_engine.py

[#272] Standardize keyword arguments.

---

CHANGELOG
hyperon_das/das.py
hyperon_das/query_engines/local_query_engine.py
hyperon_das/query_engines/query_engine_protocol.py
hyperon_das/query_engines/remote_query_engine.py
pyproject.toml
tests/integration/helpers.py
tests/integration/remote_das_info.py
tests/integration/test_das_query_api.py
tests/integration/test_iterators.py
tests/integration/test_traverse_engine.py
tests/performance/test_redis_mongo_benchmark.py
tests/unit/mock.py
tests/unit/test_das.py
tests/unit/test_traverse_engine.py

Required in the context of https://github.com/singnet/das-atom-db/issues/188

[das-atom-db#216] Removed cursor from api of get_matched*() and get_incoming_links()

---

.github/workflows/run-tests.yml

Closes https://github.com/singnet/das/issues/105

[das#105] Modify pipelines to send benchmark values only in the daily pipeline, excluding PR pipelines

---

hyperon_das/pattern_matcher/__init__.py
hyperon_das/pattern_matcher/pattern_matcher.py

For back-compatibility with DAS Gate

[HOTFIX] Create empty implementation of pattern_matcher package

---

hyperon_das/utils.py

Closes https://github.com/singnet/das-serverless-functions/issues/139

[das-serverless-functions#139]: Fix handshake message

---

hyperon_das/client.py
hyperon_das/link_filters.py
tests/integration/test_client.py
tests/performance/conftest.py
tests/performance/test_redis_mongo_benchmark.py

Fixed
- Link generation, allowing links with strength 0
- Query using index, added indexed keyword to use index
- Commented query using 3 variables to reduce test duration

[FIX] Fix performance tests

---

hyperon_das/cache/iterators.py
hyperon_das/client.py
hyperon_das/context.py
hyperon_das/das.py
hyperon_das/query_engines/local_query_engine.py
hyperon_das/query_engines/query_engine_protocol.py
hyperon_das/query_engines/remote_query_engine.py
tests/integration/helpers.py
tests/integration/test_client.py
tests/integration/test_das_query_api.py
tests/integration/test_iterators.py
tests/integration/test_local_das.py
tests/integration/test_metta_api.py
tests/integration/test_remote_das.py
tests/unit/mock.py
tests/unit/test_cache_controller.py
tests/unit/test_context.py
tests/unit/test_das.py
tests/unit/test_queries.py
tests/utils.py

Closes #354 
Relates to https://github.com/singnet/das-atom-db/issues/247

[#354] syncing with the new Atom DB

---

.black.cfg
hyperon_das/tokenizer.py
hyperon_das/tokenizers/dict_query_tokenizer.py
hyperon_das/tokenizers/elements.py
tests/performance/test_redis_mongo_benchmark.py
tests/unit/test_dict_query_tokenizer.py
tests/unit/test_elements.py

[#355] Adding `Query [Un]Tokenizer`

---

hyperon_das/tokenizers/dict_query_tokenizer.py
hyperon_das/utils.py
tests/performance/test_redis_mongo_benchmark.py

[#355] hotfix and formatting

---

hyperon_das/utils.py

[#355] formatting

---

hyperon_das/tokenizers/elements.py

[#355] hotfix

---

.github/workflows/run-tests.yml

Closes https://github.com/singnet/das/issues/117

[das#117]: Parameterize the pipeline execution process

---

tests/performance/test_redis_mongo_benchmark.py

[FIX] Benchmark dix
